[package]
name = "tracerbench-request-key"
version = "0.1.0"
authors = ["Kris Selden <kris.selden@gmail.com>"]
license = "BSD-2-Clause"
edition = "2018"

[dependencies]
regex = "1.3"
serde = "1"
serde_derive = "1"

[dev-dependencies]
serde_cbor = "0.11"
